
###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "prins",
  "password": "ikkehackmeg;("
}
### WITH TOKEN
GET http://localhost:8080/api/task/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJwcmlucyIsImlhdCI6MTc3OTE5MzI4MiwiZXhwIjoxNzc5Mjc5NjgyfQ.Dm9jrHRZKXpKeSXX6dJcBQeK0hR3fhVsnKXdVAmQTckhbxOUi-RtE0LCwpI4B0iw
